FROM ubuntu:latest

# Comando com parâmetros fixos
# Eu posso definir parâmetros fixos para compor um cmd, alternando apenas o seu parâmetro variável
ENTRYPOINT ["echo", "Hello "]

# Comando com parâmetros variados
CMD ["World"]