FROM nginx:1.15.0-alpine

# apagar configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Irá copiar o arquivo nginx.conf para o diretório de destino do container
COPY nginx.conf /etc/nginx/conf.d

# Criando arquivo index.php em branco para não retornar erro 404 na primeira chamada
# Ele irá redirecionar forma remota ao sample-app  
RUN mkdir /var/www/html -p && touch /var/www/html/index.php
