# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o /gon/bin/cache-study -gcflags='all=-N -l' -a cmd/server/main.go"
bin = "/gon/bin/cache-study"
full_bin = "dlv exec /gon/bin/cache-study --headless --log --listen :2345 --api-version 2"
args_bin = ["server"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["docs", "tmp", "vendor", ".vscode"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
