version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  user-service:
    image: gabrielpessoa/user-service:prod
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile.prod
    env_file: ./user-service/.env
    tty: true
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    tty: true
    restart: always
    ports:
    - "8080:80"
    volumes:
    - ./nginx/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - user-service
    networks:
      - app-network

volumes:
  data-mysql:
    driver: local

networks:
  app-network:
    driver: bridge
