version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  graphql-project:
    container_name: graphql-project
    build: .
    env_file: .env
    ports:
    - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ".:/usr/src/app"
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
