version: '3.1'

services:
  app:
    build:
      context: ./
    container_name: app
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    external: true