services:

  app:
    image: app:local
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqs
    networks:
      - app-net

  sqs:
    image: localstack/localstack
    container_name: sqs
    environment:
      - SERVICES=sqs
      - PERSISTENCE=1
    ports:
      - 4566:4566 # LocalStack Gateway
      - 4510-4559:4510-4559 # external services port range
    volumes:
      - sqs-data:/var/lib/localstack
    networks:
      - app-net

volumes:
  sqs-data:
    driver: local

networks:
  app-net:
    driver: bridge
